-- Project: Retail Insights - FreshMart
-- Name: Gouri Gouthamchand Katariya
-- Objective: Analyze inventory and sales data to optimize stock management

CREATE DATABASE FreshMartDB;
USE FreshMartDB;

CREATE TABLE Categories (
    CategoryID INT PRIMARY KEY,
    CategoryName VARCHAR(50)
);

CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100),
    CategoryID INT,
    ExpiryDate DATE,
    StockCount INT,
    FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID)
);

CREATE TABLE SalesTransactions (
    TransactionID INT PRIMARY KEY,
    ProductID INT,
    Quantity INT,
    SaleDate DATE,
    TotalAmount DECIMAL(10,2),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

INSERT INTO Categories VALUES
(1, 'Dairy'),
(2, 'Snacks'),
(3, 'Beverages');

INSERT INTO Products VALUES
(101, 'Milk', 1, '2026-04-08', 60),
(102, 'Cheese', 1, '2026-05-01', 30),
(103, 'Chips', 2, '2026-06-15', 100),
(104, 'Biscuits', 2, '2026-04-06', 80),
(105, 'Juice', 3, '2026-04-10', 20);

INSERT INTO SalesTransactions VALUES
(1, 101, 10, '2026-03-25', 500),
(2, 103, 5, '2026-03-20', 200),
(3, 105, 8, '2026-02-10', 300);

SELECT * FROM Products;
SELECT * FROM Categories;
SELECT * FROM SalesTransactions;

-- Query 1: Find products expiring within 7 days with high stock

SELECT *
FROM Products
WHERE ExpiryDate BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 7 DAY)
AND StockCount > 50;

-- Expected Output:
-- Milk, Biscuits (High stock and near expiry)

-- Query 2: Identify products that have not been sold in the last 60 days

SELECT p.*
FROM Products p
LEFT JOIN SalesTransactions s 
ON p.ProductID = s.ProductID 
AND s.SaleDate >= DATE_SUB(CURDATE(), INTERVAL 60 DAY)
WHERE s.ProductID IS NULL;

-- Expected Output:
-- Products like Cheese and Biscuits (no recent sales)

-- Query 3: Calculate total revenue generated by each category for the previous month

SELECT c.CategoryName, SUM(s.TotalAmount) AS TotalRevenue
FROM SalesTransactions s
JOIN Products p ON s.ProductID = p.ProductID
JOIN Categories c ON p.CategoryID = c.CategoryID
WHERE MONTH(s.SaleDate) = MONTH(CURDATE()) - 1
GROUP BY c.CategoryName
ORDER BY TotalRevenue DESC;

-- Expected Output:
-- Dairy generates the highest revenue (500)
-- Snacks generates lower revenue (200)

-- Query 4: Find top selling products based on quantity sold

SELECT p.ProductName, SUM(s.Quantity) AS TotalSold
FROM SalesTransactions s
JOIN Products p ON s.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalSold DESC;

-- Expected Output:
-- Milk sold the highest number of units (10)
-- Juice sold 8 units
-- Chips sold 5 units

-- Query 5: Identify products with low stock (20 units or less)

SELECT *
FROM Products
WHERE StockCount <=20;

-- Expected Output:
-- Juice has low stock (20 units) and may require restocking